### ISSUE TITLE
Generate CSR Error

### ISSUE THREAD

**Issue by hongweiz-ami** [openbmc/phosphor-certificate-manager#12]
The "Generate CSR" button brings up a form successfully, however, after user fill in all the necessary information and then submit the request, there is a Error message pop up, saying "Unable to generate CSR. Try again."

**Comment by devenrao** [comment]
It is working fine for me, can you please post journal traces.

**Comment by hongweiz-ami** [comment]
Thanks Marri,
Please find attached journal traces filtered with certificate, if you need the whole journal log, please let me know.
My image was compiled with s2600wf receipe and my tree is about one week old.

Please also help point me the related commits so I can check from my side.

Thanks again.

--Hongwei

**Comment by devenrao** [comment]
Looks like the certificate existing on the system got corrupted, and the application during startup gets terminated in the process of restoring certificates.

Feb 05 20:46:21 s2600wf systemd[1]: Started Phosphor certificate manager for nslcd.
Feb 05 20:46:32 s2600wf phosphor-certificate-manager[161]: Certificate install
Feb 05 20:46:32 s2600wf phosphor-certificate-manager[160]: Certificate install
Feb 05 20:46:36 s2600wf phosphor-certificate-manager[160]: Certificate loadCert
Feb 05 20:46:36 s2600wf phosphor-certificate-manager[160]: Certificate loadCert
Feb 05 20:46:36 s2600wf phosphor-certificate-manager[160]: Certificate loadCert
Feb 05 20:46:36 s2600wf phosphor-certificate-manager[160]: Certificate loadCert
Feb 05 20:46:39 s2600wf phosphor-certificate-manager[161]: Certificate loadCert
Feb 05 20:46:39 s2600wf phosphor-certificate-manager[161]: Error occured during X509_verify_cert call, checking for known error
Feb 05 20:46:39 s2600wf phosphor-certificate-manager[161]: Invalid certificate file.

probably need to make changes so that if the certificate is corrupted it should be ignored/deleted during restoring of certificates.

will work on the fix

**Comment by hongweiz-ami** [comment]
Thanks Marri.

**Comment by devenrao** [comment]
Not able to reproduce SdBusError error being thrown? I had corruputed the certificate and restarted "systemctl restart phosphor-certificate-manager@bmcweb.service"  If you have steps to reproduce then it would be great. or else will look further

Feb 05 20:46:39 s2600wf phosphor-certificate-manager[161]: Invalid certificate file.
Feb 05 20:46:43 s2600wf phosphor-certificate-manager[161]: terminate called after throwing an instance of 'sdbusplus::exception::SdBusError'

**Comment by devenrao** [comment]
For now making changes to not to throw exception from the constructor of certificate manager which will never get the service running.

we can live if a certificate object is not created for an invalid or expired certificate.

**Comment by devenrao** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/30184
pushed the following fix
